# Make File
PROGNAME=ssl_client
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_ssl_client.c 

# SDK features
SDK_FEATURES = wlan sockets certificates freertos 

include $(RSI_SDK_PATH)/sapi/sapi.mk
