# Make File
PROGNAME=provisioning
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_provisioning_app.c

# SDK features
SDK_FEATURES = wlan sockets freertos 

include $(RSI_SDK_PATH)/sapi/sapi.mk
